image: condaforge/mambaforge:24.7.1-0
# image: gitpod/workspace-base

tasks:
- name: install mamba
  init: |
    cd /workspace

    source ${HOME}/.bashrc
    mamba create -n smudgeplot -c conda-forge r-base r-argparse r-viridis -y
    gp sync-done bundle
    
- name: activate mamba
  init: gp sync-await bundle # Wait for previous 'inits' to complete
  command: |
    cd /workspace
    mamba init bash
    mamba activate smudgeplot
    /workspace/mambaforge/bin/pip3 install click ruff

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"