image: gitpod/workspace-base
# image: condaforge/mambaforge:24.7.1-0

tasks:
- name: install mamba
  init: |
    cd /workspace
    wget "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/mambaforge && rm Mambaforge-$(uname)-$(uname -m).sh

    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n smudgeplot -c conda-forge r-base r-argparse r-viridis -y
    gp sync-done bundle
    
- name: activate mamba
  init: gp sync-await bundle # Wait for previous 'inits' to complete
  command: |
    cd /workspace
    mamba init bash
    source ~/.bashrc 
    mamba activate smudgeplot

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"