image: condaforge/mambaforge:24.7.1-0
# image: gitpod/workspace-base

tasks:
- name: install mamba
  init: |
    mamba create -n smudgeplot -c conda-forge r-base r-argparse r-viridis -y
    gp sync-done bundle
    
- name: activate mamba
  init: gp sync-await bundle # Wait for previous 'inits' to complete
  command: |
    cd /workspace
    mamba init bash
    source ~/.bashrc 
    mamba activate smudgeplot

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"